// Code generated by protoc-gen-gogo.
// source: protos/server.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/server.proto

It has these top-level messages:
	Config
*/
package protos

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// Config contains the server's configutation options.
type Config struct {
	Port *uint32 `protobuf:"varint,1,req,name=port" json:"port,omitempty"`
	// address is an optional IP address. If given, the server will only
	// listen on this address.
	Address *string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	// allow_registration controls whether new account requests will be
	// processed.
	AllowRegistration *bool  `protobuf:"varint,3,opt,name=allow_registration,def=1" json:"allow_registration,omitempty"`
	XXX_unrecognized  []byte `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}

const Default_Config_AllowRegistration bool = true

func (m *Config) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *Config) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *Config) GetAllowRegistration() bool {
	if m != nil && m.AllowRegistration != nil {
		return *m.AllowRegistration
	}
	return Default_Config_AllowRegistration
}

func init() {
}
