// Code generated by protoc-gen-go from "github.com/agl/pond/client/protos/client.proto"
// DO NOT EDIT!

package protos

import proto "code.google.com/p/goprotobuf/proto"
import "encoding/json"
import "math"
import protos1 "github.com/agl/pond/protos"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Contact struct {
	Id                  *uint64 `protobuf:"fixed64,1,req,name=id" json:"id,omitempty"`
	Name                *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	GroupKey            []byte  `protobuf:"bytes,3,req,name=group_key" json:"group_key,omitempty"`
	KeyExchangeBytes    []byte  `protobuf:"bytes,4,opt,name=key_exchange_bytes" json:"key_exchange_bytes,omitempty"`
	TheirGroup          []byte  `protobuf:"bytes,5,opt,name=their_group" json:"their_group,omitempty"`
	MyGroupKey          []byte  `protobuf:"bytes,6,opt,name=my_group_key" json:"my_group_key,omitempty"`
	Generation          *uint32 `protobuf:"varint,7,opt,name=generation" json:"generation,omitempty"`
	TheirServer         *string `protobuf:"bytes,8,opt,name=their_server" json:"their_server,omitempty"`
	TheirPub            []byte  `protobuf:"bytes,9,opt,name=their_pub" json:"their_pub,omitempty"`
	TheirIdentityPublic []byte  `protobuf:"bytes,10,opt,name=their_identity_public" json:"their_identity_public,omitempty"`
	LastPrivate         []byte  `protobuf:"bytes,11,opt,name=last_private" json:"last_private,omitempty"`
	CurrentPrivate      []byte  `protobuf:"bytes,12,opt,name=current_private" json:"current_private,omitempty"`
	TheirLastPublic     []byte  `protobuf:"bytes,13,opt,name=their_last_public" json:"their_last_public,omitempty"`
	TheirCurrentPublic  []byte  `protobuf:"bytes,14,opt,name=their_current_public" json:"their_current_public,omitempty"`
	IsPending           *bool   `protobuf:"varint,15,opt,name=is_pending,def=0" json:"is_pending,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (this *Contact) Reset()         { *this = Contact{} }
func (this *Contact) String() string { return proto.CompactTextString(this) }
func (*Contact) ProtoMessage()       {}

const Default_Contact_IsPending bool = false

func (this *Contact) GetId() uint64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Contact) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Contact) GetGroupKey() []byte {
	if this != nil {
		return this.GroupKey
	}
	return nil
}

func (this *Contact) GetKeyExchangeBytes() []byte {
	if this != nil {
		return this.KeyExchangeBytes
	}
	return nil
}

func (this *Contact) GetTheirGroup() []byte {
	if this != nil {
		return this.TheirGroup
	}
	return nil
}

func (this *Contact) GetMyGroupKey() []byte {
	if this != nil {
		return this.MyGroupKey
	}
	return nil
}

func (this *Contact) GetGeneration() uint32 {
	if this != nil && this.Generation != nil {
		return *this.Generation
	}
	return 0
}

func (this *Contact) GetTheirServer() string {
	if this != nil && this.TheirServer != nil {
		return *this.TheirServer
	}
	return ""
}

func (this *Contact) GetTheirPub() []byte {
	if this != nil {
		return this.TheirPub
	}
	return nil
}

func (this *Contact) GetTheirIdentityPublic() []byte {
	if this != nil {
		return this.TheirIdentityPublic
	}
	return nil
}

func (this *Contact) GetLastPrivate() []byte {
	if this != nil {
		return this.LastPrivate
	}
	return nil
}

func (this *Contact) GetCurrentPrivate() []byte {
	if this != nil {
		return this.CurrentPrivate
	}
	return nil
}

func (this *Contact) GetTheirLastPublic() []byte {
	if this != nil {
		return this.TheirLastPublic
	}
	return nil
}

func (this *Contact) GetTheirCurrentPublic() []byte {
	if this != nil {
		return this.TheirCurrentPublic
	}
	return nil
}

func (this *Contact) GetIsPending() bool {
	if this != nil && this.IsPending != nil {
		return *this.IsPending
	}
	return Default_Contact_IsPending
}

type Inbox struct {
	Id               *uint64 `protobuf:"fixed64,1,req,name=id" json:"id,omitempty"`
	From             *uint64 `protobuf:"fixed64,2,req,name=from" json:"from,omitempty"`
	ReceivedTime     *int64  `protobuf:"varint,3,req,name=received_time" json:"received_time,omitempty"`
	Acked            *bool   `protobuf:"varint,4,req,name=acked" json:"acked,omitempty"`
	Message          []byte  `protobuf:"bytes,5,opt,name=message" json:"message,omitempty"`
	Read             *bool   `protobuf:"varint,6,req,name=read" json:"read,omitempty"`
	Sealed           []byte  `protobuf:"bytes,7,opt,name=sealed" json:"sealed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Inbox) Reset()         { *this = Inbox{} }
func (this *Inbox) String() string { return proto.CompactTextString(this) }
func (*Inbox) ProtoMessage()       {}

func (this *Inbox) GetId() uint64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Inbox) GetFrom() uint64 {
	if this != nil && this.From != nil {
		return *this.From
	}
	return 0
}

func (this *Inbox) GetReceivedTime() int64 {
	if this != nil && this.ReceivedTime != nil {
		return *this.ReceivedTime
	}
	return 0
}

func (this *Inbox) GetAcked() bool {
	if this != nil && this.Acked != nil {
		return *this.Acked
	}
	return false
}

func (this *Inbox) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *Inbox) GetRead() bool {
	if this != nil && this.Read != nil {
		return *this.Read
	}
	return false
}

func (this *Inbox) GetSealed() []byte {
	if this != nil {
		return this.Sealed
	}
	return nil
}

type Outbox struct {
	Id               *uint64 `protobuf:"fixed64,1,req,name=id" json:"id,omitempty"`
	To               *uint64 `protobuf:"fixed64,2,req,name=to" json:"to,omitempty"`
	Server           *string `protobuf:"bytes,3,req,name=server" json:"server,omitempty"`
	Created          *int64  `protobuf:"varint,4,req,name=created" json:"created,omitempty"`
	Sent             *int64  `protobuf:"varint,5,opt,name=sent" json:"sent,omitempty"`
	Message          []byte  `protobuf:"bytes,6,req,name=message" json:"message,omitempty"`
	Request          []byte  `protobuf:"bytes,7,opt,name=request" json:"request,omitempty"`
	Acked            *int64  `protobuf:"varint,8,opt,name=acked" json:"acked,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Outbox) Reset()         { *this = Outbox{} }
func (this *Outbox) String() string { return proto.CompactTextString(this) }
func (*Outbox) ProtoMessage()       {}

func (this *Outbox) GetId() uint64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Outbox) GetTo() uint64 {
	if this != nil && this.To != nil {
		return *this.To
	}
	return 0
}

func (this *Outbox) GetServer() string {
	if this != nil && this.Server != nil {
		return *this.Server
	}
	return ""
}

func (this *Outbox) GetCreated() int64 {
	if this != nil && this.Created != nil {
		return *this.Created
	}
	return 0
}

func (this *Outbox) GetSent() int64 {
	if this != nil && this.Sent != nil {
		return *this.Sent
	}
	return 0
}

func (this *Outbox) GetMessage() []byte {
	if this != nil {
		return this.Message
	}
	return nil
}

func (this *Outbox) GetRequest() []byte {
	if this != nil {
		return this.Request
	}
	return nil
}

func (this *Outbox) GetAcked() int64 {
	if this != nil && this.Acked != nil {
		return *this.Acked
	}
	return 0
}

type Draft struct {
	Id               *uint64                       `protobuf:"fixed64,1,req,name=id" json:"id,omitempty"`
	Created          *int64                        `protobuf:"varint,2,req,name=created" json:"created,omitempty"`
	To               *uint64                       `protobuf:"fixed64,3,opt,name=to" json:"to,omitempty"`
	Body             *string                       `protobuf:"bytes,4,req,name=body" json:"body,omitempty"`
	InReplyTo        *uint64                       `protobuf:"fixed64,5,opt,name=in_reply_to" json:"in_reply_to,omitempty"`
	Attachments      []*protos1.Message_Attachment `protobuf:"bytes,6,rep,name=attachments" json:"attachments,omitempty"`
	Detachments      []*protos1.Message_Detachment `protobuf:"bytes,7,rep,name=detachments" json:"detachments,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (this *Draft) Reset()         { *this = Draft{} }
func (this *Draft) String() string { return proto.CompactTextString(this) }
func (*Draft) ProtoMessage()       {}

func (this *Draft) GetId() uint64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Draft) GetCreated() int64 {
	if this != nil && this.Created != nil {
		return *this.Created
	}
	return 0
}

func (this *Draft) GetTo() uint64 {
	if this != nil && this.To != nil {
		return *this.To
	}
	return 0
}

func (this *Draft) GetBody() string {
	if this != nil && this.Body != nil {
		return *this.Body
	}
	return ""
}

func (this *Draft) GetInReplyTo() uint64 {
	if this != nil && this.InReplyTo != nil {
		return *this.InReplyTo
	}
	return 0
}

type State struct {
	Identity         []byte     `protobuf:"bytes,1,req,name=identity" json:"identity,omitempty"`
	Public           []byte     `protobuf:"bytes,2,req,name=public" json:"public,omitempty"`
	Private          []byte     `protobuf:"bytes,3,req,name=private" json:"private,omitempty"`
	Server           *string    `protobuf:"bytes,4,req,name=server" json:"server,omitempty"`
	Group            []byte     `protobuf:"bytes,5,req,name=group" json:"group,omitempty"`
	GroupPrivate     []byte     `protobuf:"bytes,6,req,name=group_private" json:"group_private,omitempty"`
	Generation       *uint32    `protobuf:"varint,7,req,name=generation" json:"generation,omitempty"`
	Contacts         []*Contact `protobuf:"bytes,8,rep,name=contacts" json:"contacts,omitempty"`
	Inbox            []*Inbox   `protobuf:"bytes,9,rep,name=inbox" json:"inbox,omitempty"`
	Outbox           []*Outbox  `protobuf:"bytes,10,rep,name=outbox" json:"outbox,omitempty"`
	Drafts           []*Draft   `protobuf:"bytes,11,rep,name=drafts" json:"drafts,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *State) Reset()         { *this = State{} }
func (this *State) String() string { return proto.CompactTextString(this) }
func (*State) ProtoMessage()       {}

func (this *State) GetIdentity() []byte {
	if this != nil {
		return this.Identity
	}
	return nil
}

func (this *State) GetPublic() []byte {
	if this != nil {
		return this.Public
	}
	return nil
}

func (this *State) GetPrivate() []byte {
	if this != nil {
		return this.Private
	}
	return nil
}

func (this *State) GetServer() string {
	if this != nil && this.Server != nil {
		return *this.Server
	}
	return ""
}

func (this *State) GetGroup() []byte {
	if this != nil {
		return this.Group
	}
	return nil
}

func (this *State) GetGroupPrivate() []byte {
	if this != nil {
		return this.GroupPrivate
	}
	return nil
}

func (this *State) GetGeneration() uint32 {
	if this != nil && this.Generation != nil {
		return *this.Generation
	}
	return 0
}

func init() {
}
